spring.application.name=Project2


spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres

spring.datasource.username=postgres.qtrcfhakexxlmnmtzuog
spring.datasource.password=DayGIgW7RdmkXj9o

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.databse/.platform=

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

#JWT Properties
jwt.secret=60b10268ebeb7f2778550fb59d757a41c794dde0e4a18eff64f8370ee021087e
jwt.expiration=3600000

#jwt.secret = &{SECRET}

