spring.application.name=Project2

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${DB_PASSWORD}





spring.datasource.username=postgres.qtrcfhakexxlmnmtzuog
spring.datasource.password=DayGIgW7RdmkXj9o

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.databse/.platform=

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

#JWT Properties
${JWT_SECRET}=60b10268ebeb7f2778550fb59d757a41c794dde0e4a18eff64f8370ee021087e
${JWT_EXP}=3600000

#jwt.secret = &{SECRET}

spring.datasource.url=jdbc:mysql://hayabusa.proxy.rlwy.net:50983
spring.datasource.username=root
spring.datasource.password=SbYUKLVIVdAnkMdkDuRYxASaiOWbrPZB